### ISSUE TITLE
build.phonegap.com

### ISSUE THREAD

**Issue by krassswr** [macdonst/cordova-plugin-compat#1]
Please make this plugin compatible with build.phonegap.com.
When I insert other plugin that require this plugin, build.phonegap.com says 'malformed config.xml' this is because of additional messace that is printed in console when plugin is installed.

**Comment by macdonst** [comment]
@krassswr Don't use this plugin, use the official one at:

https://github.com/apache/cordova-plugin-compat

This repo is only where I started the work for what was then donated to Apache.

If you have any issues with it open it at:

https://issues.apache.org/jira/browse/CB/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel
